website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

#User schema
class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))

class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text, nullable=False)
    date_created = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    #initialize flask
    app.config['SECRET_KEY'] = 'wfjw89a3oi32hr98hfa3he39hr'
    #for encrypting session data, random string, put this in env before production

    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    #import then register blueprints
    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/")
    #prefix defines the route so prefix /data would have all routes under /data/route

    from .models import User

    create_database(app)
    #If the db isn't created yet, create it

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        with app.app_context():
            db.create_all()
        print("Database Created")

website/auth.py
#auth routes setup
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully", category='success')
                login_user(user, remember=True)#remember for this session
                return redirect(url_for('views.home'))
            else:
                flash("Incorrect password", category='error')
        else:
            flash("Email not found", category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash("Email must be greater than 3 characters", category='error')
        elif len(first_name) < 2:
            flash("First name must have more than 1 character", category='error')
        elif password1 != password2:
            flash("Passwords don't match!", category='error')
        elif len(password1) < 7:
            flash("Password needs to be more than 6 characters", category='error')
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            flash("Account created.", category='success')
            login_user(new_user, remember=True)  # remember for this session
            return redirect(url_for('views.home'))
    return render_template("sign_up.html", user=current_user)

website/views.py
#routes for the website
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required, current_user
from .models import News
from flask import jsonify
from . import db
import json
from datetime import datetime
from . import news_summary
import asyncio
from . import format
views = Blueprint('views', __name__)
#define views blueprint


#define home route
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    user_news = News.query.filter_by(user_id=current_user.id).all()
    unique_dates = sorted(set(n.date_created.date() for n in user_news), reverse=True)
    return render_template("home.html", user=current_user, unique_dates=unique_dates)

@views.route("/generate-news", methods=["POST"])
def generate_news():
    try:
        data = request.json
        article_count = data.get("count", 5)
        article_filter = data.get("filter", "")
        asyncio.run(news_summary.news_review(article_count, article_filter))
        return jsonify({"message": "News generated successfully"}), 200
    except Exception as e:
        flash("Failed to get the news", "error")
        return jsonify({"error": str(e)})

@views.route('/news/<date>', methods=['GET'])
@login_required
def news_by_date(date):
    try:
        date_obj = datetime.strptime(date, "%m-%d-%Y").date()
    except ValueError:
        flash("Invalid date format.", category="error")
        return redirect(url_for("views.home"))
    news_entries = News.query.filter_by(user_id=current_user.id).filter(db.func.date(News.date_created) == date_obj).all()
    for news in news_entries:
        news.content = format.format_news_text(news.content)
    return render_template("news.html", user=current_user, news_entries=news_entries, date=date)


@views.route('/delete-news', methods=['POST'])
@login_required
def delete_news():
    data = json.loads(request.data)
    news_id = data.get('newsId')
    news = News.query.get(news_id)
    if news and news.user_id == current_user.id:
        db.session.delete(news)
        db.session.commit()
        return jsonify({"success": True})
    return jsonify({"success":False, "error":"Unauthorized"}), 403

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
    />
    <link
            rel="stylesheet"
            href="../static/styles.css"
            crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                {% endif %}
            </div>
        </div>
    </nav>
<!--Flash messages-->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% else %}
                    <div class="alert success alert-dismissable fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
<style>
    .container{
        padding-top: 10px;
    }
</style>
<script src="{{ url_for('static', filename='index.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="content-container">
  <h1 align="center" class="main-heading">AI News Buddy</h1>
  <p align="center">
  </p>
  <p align="center">
  </p>
  
  <div class="buttons-container">
    <div class="buttons-div">
      

      <button class="get-button btn btn-primary">Get Summaries</button>
    </div>
    <div class="dropdown">
      <button
        class="dropdown-button btn btn-secondary dropdown-toggle"
        type="button"
        data-bs-toggle="dropdown"
        data-bs-display="static"
        data-flip="false"
        aria-expanded="false"
      >
        Filter
      </button>
      <ul class="dropdown-menu dropdown-menu-end">
        <li><button class="mb-1 dropdown-item">All</button></li>
        <li><button class="mb-2 dropdown-item">Politics</button></li>
        <li><button class="mb-3 dropdown-item">Custom Filter</button></li>
      </ul>
    </div>
    <div class="dropdown">
        <button
          class="dropdown-button2 btn btn-secondary dropdown-toggle"
          type="button"
          data-bs-toggle="dropdown"
          data-bs-display="static"
          data-flip="false"
          aria-expanded="false"
        >
          5
        </button>
        <ul class="dropdown-menu dropdown-menu-end">
          <li><button class="mbt-1 dropdown-item">5</button></li>
          <li><button class="mbt-2 dropdown-item">8</button></li>
          <li><button class="mbt-3 dropdown-item">10</button></li>
          <li><button class="mbt-4 dropdown-item">15</button></li>
        </ul>
      </div>
    <input
        class="custom-input hidden"
        type="text"
        placeholder="Enter a custom filter"
      />
    
  </div>
    <span class="loader hidden"></span>
    <div class="card-container">
        {% for date in unique_dates %}
        <div class="card my-3">
            <div class="card-body">
                <h5 class="card-title">{{ date.strftime('%B %d, %Y') }}</h5>
                <a href="{{ url_for('views.news_by_date', date=date.strftime('%m-%d-%Y')) }}" class="btn btn-info">View</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email">
          Email Address
        </label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
      </div>
      <div class="form-group">
        <label for="password">
          Password
        </label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
      </div>
      <br/>
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

website/templates/news.html
{% extends "base.html" %}
{% block content %}
<h1>News for {{ date }}</h1>

{% for news in news_entries %}
    <div class="card my-3">
        <div class="card-body">
            <p class="card-text">{{ news.content | safe }}</p>
            <button class="btn btn-danger" onclick="deleteNews('{{ news.id }}')">Delete</button>
        </div>
    </div>
{% endfor %}

<a href="{{ url_for('views.home') }}" class="btn btn-secondary">Back to Dates</a>

<script>
    function deleteNews(newsId) {
        fetch("/delete-news", {
            method: "POST",
            body: JSON.stringify({ newsId: newsId }),
            headers: { "Content-Type": "application/json" }
        }).then((_res) => {
            location.href = "/";
        });
    }
</script>

{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Signup{% endblock %}

{% block content %}
    <form method="POST">
      <h3 align="center">Sign Up</h3>
      <div class="form-group">
        <label for="email">
          Email Address
        </label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
      </div>
      <div class="form-group">
        <label for="firstName">
          First Name
        </label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name">
      </div>
      <div class="form-group">
        <label for="password1">
          Password
        </label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password">
      </div>
      <div class="form-group">
        <label for="password2">
          Confirm Password
        </label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="">
      </div>
      <br/>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}